#ifndef __MALI_REG_RTD119X_H__
#define __MALI_REG_RTD119X_H__

#define RTK_MALI_OFFSET_L2        0x16000
#define RTK_MALI_OFFSET_PMU       0x1c000
#define RTK_MALI_OFFSET_GP        0x00000
#define RTK_MALI_OFFSET_GP_MMU    0x26000
#define RTK_MALI_OFFSET_PP0       0x30000
#define RTK_MALI_OFFSET_PP0_MMU   0x27000
#define RTK_MALI_OFFSET_PP1       0x2e000
#define RTK_MALI_OFFSET_PP1_MMU   0x28000
#define RTK_MALI_OFFSET_INVALID   0xfffff

#define MALI_OFFSET_GP                    RTK_MALI_OFFSET_GP
#define MALI_OFFSET_GP_MMU                RTK_MALI_OFFSET_GP_MMU

#define MALI_OFFSET_PP0                   RTK_MALI_OFFSET_PP0
#define MALI_OFFSET_PP0_MMU               RTK_MALI_OFFSET_PP0_MMU
#define MALI_OFFSET_PP1                   RTK_MALI_OFFSET_PP1
#define MALI_OFFSET_PP1_MMU               RTK_MALI_OFFSET_PP1_MMU
#define MALI_OFFSET_PP2                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP2_MMU               RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP3                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP3_MMU               RTK_MALI_OFFSET_INVALID

#define MALI_OFFSET_PP4                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP4_MMU               RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP5                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP5_MMU               RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP6                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP6_MMU               RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP7                   RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_PP7_MMU               RTK_MALI_OFFSET_INVALID

#define MALI_OFFSET_L2_RESOURCE0          RTK_MALI_OFFSET_L2
#define MALI_OFFSET_L2_RESOURCE1          RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_L2_RESOURCE2          RTK_MALI_OFFSET_INVALID

#define MALI400_OFFSET_L2_CACHE0          MALI_OFFSET_L2_RESOURCE0
#define MALI450_OFFSET_L2_CACHE0          MALI_OFFSET_L2_RESOURCE1
#define MALI450_OFFSET_L2_CACHE1          MALI_OFFSET_L2_RESOURCE0
#define MALI450_OFFSET_L2_CACHE2          MALI_OFFSET_L2_RESOURCE2
#define MALI470_OFFSET_L2_CACHE1          MALI_OFFSET_L2_RESOURCE0

#define MALI_OFFSET_BCAST                 RTK_MALI_OFFSET_INVALID
#define MALI_OFFSET_DLBU                  RTK_MALI_OFFSET_INVALID

#define MALI_OFFSET_PP_BCAST              RTK_MALI_OFFSET_L2
#define MALI_OFFSET_PP_BCAST_MMU          RTK_MALI_OFFSET_INVALID

#define MALI_OFFSET_PMU                   RTK_MALI_OFFSET_PMU
#define MALI_OFFSET_DMA                   RTK_MALI_OFFSET_INVALID

#endif
