obj-$(CONFIG_RTK_REGISTER_TRACKER) += rdbg.o
obj-$(CONFIG_RTK_POWER_TRACKER) += power-tracker.o
obj-$(CONFIG_RTK_POWER_TRACKER_MALI) += power-tracker-mali.o
obj-$(CONFIG_RTK_POWER_TRACKER_TEST) += power-tracker-test.o
obj-$(CONFIG_RTK_SRR_READER) += srr_read.o
